/* Build source for mica/avatar.js. The published module is generated by
 * tools/build-avatar.ts so Blobatar stays opt-in without requiring consumers
 * to resolve a bare package import in the browser. */

import { palette, traits } from "blobatar";

const PROPERTIES = [
  "--m-avatar-content-color",
  "--m-avatar-body-color",
  "--m-avatar-eye-color",
  "--m-avatar-body-inset-block",
  "--m-avatar-body-inset-inline",
  "--m-avatar-body-x",
  "--m-avatar-body-y",
  "--m-avatar-eye-top",
  "--m-avatar-eye-left",
  "--m-avatar-eye-width",
  "--m-avatar-eye-height",
  "--m-avatar-eye-gap",
  "--m-avatar-eye-drop",
];

const percent = (value) => `${Math.round(value * 100) / 100}%`;

class MAvatar extends HTMLElement {
  static observedAttributes = ["blobatar"];

  connectedCallback() {
    this.#update();
  }

  attributeChangedCallback() {
    if (this.isConnected) this.#update();
  }

  #update() {
    const seed = this.getAttribute("blobatar");
    if (seed === null) {
      for (const property of PROPERTIES) this.style.removeProperty(property);
      return;
    }

    const t = traits(seed);
    const colors = palette(t.num("hue", 0, 360), true, t("tone"));

    this.style.setProperty("--m-avatar-content-color", "transparent");
    this.style.setProperty("--m-avatar-body-color", colors.head);
    this.style.setProperty("--m-avatar-eye-color", colors.eye);
    this.style.setProperty(
      "--m-avatar-body-inset-block",
      percent(t.num("mica.body.block", 11, 16)),
    );
    this.style.setProperty(
      "--m-avatar-body-inset-inline",
      percent(t.num("mica.body.inline", 10, 16)),
    );
    this.style.setProperty("--m-avatar-body-x", percent(t.jitter("mica.body.x", 2)));
    this.style.setProperty("--m-avatar-body-y", percent(t.jitter("mica.body.y", 2)));
    this.style.setProperty("--m-avatar-eye-top", percent(t.num("mica.eye.top", 42, 49)));
    this.style.setProperty("--m-avatar-eye-left", percent(t.num("mica.eye.left", 36, 40)));
    this.style.setProperty("--m-avatar-eye-width", percent(t.num("mica.eye.width", 2.5, 3.5)));
    this.style.setProperty("--m-avatar-eye-height", percent(t.num("mica.eye.height", 7.5, 10)));
    this.style.setProperty("--m-avatar-eye-gap", percent(t.num("mica.eye.gap", 19, 23)));
    this.style.setProperty("--m-avatar-eye-drop", percent(t.jitter("mica.eye.drop", 2)));
  }
}

if (!customElements.get("m-avatar")) customElements.define("m-avatar", MAvatar);
