#!/usr/bin/env bun

import { dirname, join } from "node:path";

const ROOT = dirname(import.meta.dir);
const result = await Bun.build({
  entrypoints: [join(import.meta.dir, "avatar.js")],
  target: "browser",
  format: "esm",
  minify: false,
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const bundle = await result.outputs[0].text();
const banner = `/*! mica/avatar.js — generated by tools/build-avatar.ts.
 * Includes Blobatar 2.4.0 (MIT); see THIRD_PARTY_LICENSES.md. */\n`;
await Bun.write(join(ROOT, "avatar.js"), banner + bundle);
console.log(`wrote avatar.js (${(banner.length + bundle.length).toLocaleString()} bytes)`);
